package com.pms.dischargesummary.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

public record DischargeSummaryDto(
        Long id,
        Long admissionId,
        // --- Read-only patient/admission context, ignored on save ---
        String patientUhid,
        String patientName,
        String gender,
        Integer age,
        String mobileNumber,
        String address,
        String admissionNumber,
        String roomNumber,
        LocalDateTime admissionDate,
        LocalDateTime dischargeDate,
        String maritalStatus,
        String occupation,
        String primaryConsultant,
        // --- Header ---
        List<String> consultants,
        String referredBy,
        Double weightKg,
        String rcnNo,
        String title,
        String bloodGroup,
        List<String> diagnosis,
        List<String> procedures,
        // --- History ---
        String briefHistory,
        String pastHistory,
        String personalHistory,
        String surgicalHistory,
        String familyHistory,
        String intolerance,
        String immunization,
        String menstrualHistory,
        String maritalHistory,
        String obstetricHistory,
        // --- Clinical examination ---
        String generalExamination,
        String tempF,
        String pr,
        String bp,
        String rr,
        String spo2,
        String cbg,
        String cvs,
        String rs,
        String abdomen,
        String cns,
        String localExamination,
        // --- Investigations ---
        String investigationXray,
        String investigationEcg,
        String investigationEcho,
        String investigationTmt,
        String investigationUsgAbdomen,
        String investigationUsgPelvis,
        String investigationEndoscopy,
        String investigationColonoscopy,
        String investigationSigmoidoscopy,
        String investigationMriScan,
        String investigationDopplerStudy,
        String investigationNerveConduction,
        // --- Blood investigations ---
        LocalDate bloodInvestigationDate,
        String hemoglobin,
        String bloodUrea,
        String srCreatinine,
        String sodium,
        String potassium,
        String hba1c,
        String orEnclosed,
        // --- Coronary angiogram ---
        LocalDate angiogramDate,
        String angiogramSite,
        String angiogramArtery,
        String angiogramProcedure,
        String lmca,
        String lad,
        String lcx,
        String rca,
        List<String> impression,
        String recommendation,
        String treatmentGiven,
        // --- Surgery notes ---
        List<DischargeSurgeryProcedureDto> surgeryProcedures,
        String courseInHospital,
        // --- Advise drugs ---
        List<DischargeAdviseDrugDto> adviseDrugs,
        // --- Discharge advice ---
        String review,
        String dietAdvice,
        String physiotherapy,
        String physicalActivity,
        String advice,
        String reviewDescription,
        String conditionAtDischarge,
        String emergencyContactNumbers,
        List<String> emergencySymptoms,
        String checkedBy,
        String consultantSignOff) {
}
