CREATE TABLE discharge_summary (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    admission_id BIGINT NOT NULL,
    consultants_text TEXT NULL,
    referred_by VARCHAR(255) NULL,
    weight_kg DOUBLE NULL,
    rcn_no VARCHAR(100) NULL,
    title VARCHAR(255) NULL,
    blood_group VARCHAR(20) NULL,
    diagnosis_text TEXT NULL,
    procedures_text TEXT NULL,
    brief_history TEXT NULL,
    past_history TEXT NULL,
    personal_history TEXT NULL,
    surgical_history TEXT NULL,
    family_history TEXT NULL,
    intolerance TEXT NULL,
    immunization TEXT NULL,
    menstrual_history TEXT NULL,
    marital_history TEXT NULL,
    obstetric_history TEXT NULL,
    general_examination TEXT NULL,
    temp_f VARCHAR(20) NULL,
    pr VARCHAR(20) NULL,
    bp VARCHAR(20) NULL,
    rr VARCHAR(20) NULL,
    spo2 VARCHAR(20) NULL,
    cbg VARCHAR(20) NULL,
    cvs TEXT NULL,
    rs TEXT NULL,
    abdomen TEXT NULL,
    cns TEXT NULL,
    local_examination TEXT NULL,
    investigation_xray TEXT NULL,
    investigation_ecg TEXT NULL,
    investigation_echo TEXT NULL,
    investigation_tmt TEXT NULL,
    investigation_usg_abdomen TEXT NULL,
    investigation_usg_pelvis TEXT NULL,
    investigation_endoscopy TEXT NULL,
    investigation_colonoscopy TEXT NULL,
    investigation_sigmoidoscopy TEXT NULL,
    investigation_mri_scan TEXT NULL,
    investigation_doppler_study TEXT NULL,
    investigation_nerve_conduction TEXT NULL,
    blood_investigation_date DATE NULL,
    hemoglobin VARCHAR(50) NULL,
    blood_urea VARCHAR(50) NULL,
    sr_creatinine VARCHAR(50) NULL,
    sodium VARCHAR(50) NULL,
    potassium VARCHAR(50) NULL,
    hba1c VARCHAR(50) NULL,
    or_enclosed VARCHAR(100) NULL,
    angiogram_date DATE NULL,
    angiogram_site VARCHAR(100) NULL,
    angiogram_artery VARCHAR(100) NULL,
    angiogram_procedure TEXT NULL,
    lmca VARCHAR(255) NULL,
    lad VARCHAR(255) NULL,
    lcx VARCHAR(255) NULL,
    rca VARCHAR(255) NULL,
    impression_text TEXT NULL,
    recommendation TEXT NULL,
    treatment_given TEXT NULL,
    course_in_hospital TEXT NULL,
    review TEXT NULL,
    diet_advice TEXT NULL,
    physiotherapy TEXT NULL,
    physical_activity TEXT NULL,
    advice TEXT NULL,
    review_description TEXT NULL,
    condition_at_discharge TEXT NULL,
    emergency_contact_numbers VARCHAR(255) NULL,
    emergency_symptoms_text TEXT NULL,
    checked_by VARCHAR(255) NULL,
    consultant_sign_off VARCHAR(255) NULL,
    created_at TIMESTAMP(6) NULL,
    updated_at TIMESTAMP(6) NULL,
    CONSTRAINT fk_discharge_summary_admission FOREIGN KEY (admission_id) REFERENCES admission (id),
    CONSTRAINT uk_discharge_summary_admission UNIQUE (admission_id)
);

CREATE TABLE discharge_surgery_procedure (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    discharge_summary_id BIGINT NOT NULL,
    procedure_name VARCHAR(255) NULL,
    surgeon_name VARCHAR(255) NULL,
    assistant_surgeon_name VARCHAR(255) NULL,
    anaesthetist_name VARCHAR(255) NULL,
    date_of_surgery DATE NULL,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_discharge_surgery_procedure_summary FOREIGN KEY (discharge_summary_id) REFERENCES discharge_summary (id)
);

CREATE TABLE discharge_advise_drug (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    discharge_summary_id BIGINT NOT NULL,
    drug_name VARCHAR(255) NOT NULL,
    advise_type VARCHAR(16) NOT NULL DEFAULT 'REGULAR',
    dose VARCHAR(50) NULL,
    morning VARCHAR(20) NULL,
    afternoon VARCHAR(20) NULL,
    evening VARCHAR(20) NULL,
    night VARCHAR(20) NULL,
    route VARCHAR(50) NULL,
    relationship_with_meal VARCHAR(100) NULL,
    duration VARCHAR(50) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_discharge_advise_drug_summary FOREIGN KEY (discharge_summary_id) REFERENCES discharge_summary (id)
);
